In [1]:
import numpy as np 
import cv2 
import pandas as pd 
from matplotlib import pyplot as plt 
import matplotlib 
import os 
matplotlib.use('TKAgg')

import tensorflow as tf 
from tensorflow import keras 
from tensorflow.keras.applications.vgg16 import VGG16 
from tensorflow.keras.preprocessing.image import ImageDataGenerator 
from tensorflow.keras import callbacks 
from tensorflow.keras.callbacks import EarlyStopping 
from tensorflow.keras.callbacks import CSVLogger 
from sklearn.model_selection import train_test_split 
from tensorflow.keras.models import load_model

import pickle 


In [1]:
path=r'E:\python\basic code\R-cNN\Images'
path1=r'E:\python\basic code\R-cNN\Airplanes_Annotations'

In [3]:
#generates bounding box 
img_data=cv2.imread(os.path.join(path,"airplane_012.jpg"))
ss=cv2.ximgproc.segmentation.createSelectiveSearchSegmentation()
ss.setBaseImage(img_data)
ss.switchToSelectiveSearchFast()
rect=ss.process()
for x,y,w,h in rect:
    cv2.rectangle(img_data,(x,y),(x+w,y+h),(0,255,0),2)
    
cv2.imshow('img',img_data)

In [6]:
x,y,h,w=rect[0]

In [3]:
def cal_iou(gt,pred):
    x1=max(gt[0],pred[0])
    y1=max(gt[1],pred[1])
    x2=min(gt[2],pred[2])
    y2=min(gt[3],pred[3])
    #calculating the area of the intersection region 
    width=max(0,x2-x1)
    height=max(0,y2-y1)
    intersection_area=(width+1)*(height+1)
    total_area=(gt[2]-gt[0]+1)*(gt[3]-gt[1]+1)+((pred[2]-pred[0]+1)*(pred[3]-pred[1]+1))
    iou=intersection_area/(total_area-intersection_area)
    return iou

In [10]:
df=pd.read_csv(os.path.join(path1,"airplane_012.csv"))
for i in df.values:
    x1,y1,x2,y2=i[0].split(" ")
    print(np.array([int(x1),int(y1),int(x2),int(y2)]))
    


[ 29  12 123  98]
[ 82 137 186 227]


In [23]:
dt1=cv2.imread(os.path.join(path,"airplane_012.jpg"))
plt.imshow(dt1[137:228,82:187])
plt.show()

In [4]:
#finding the bounding box which has iou larger than 0.7 and smaller than 0.3
ss=cv2.ximgproc.segmentation.createSelectiveSearchSegmentation()
train_img=[]
train_label=[]
for i,f in enumerate(os.listdir(path)):
    if f.startswith('airplane'):
        img_name=f.split('.')[0]
        img_data=cv2.imread(os.path.join(path,f))
        
        
        ss.setBaseImage(img_data)
        ss.switchToSelectiveSearchFast()
        rect=ss.process()
        #corresponding dataframe
        df=pd.read_csv(os.path.join(path1,img_name+".csv"))
        img_copy=img_data.copy()
        counter=0
        bcounter=0
        flag=0
        fflag=0
        bflag=0
        for num,bbox in enumerate(rect):
            if num<1000 and flag ==0 :
                x,y,w,h=bbox
                pred=[x,y,x+w,y+h]
            
                for box in df.values:
                    x1,y1,x2,y2=box[0].split(" ")
                    gt=np.array([int(x1),int(y1),int(x2),int(y2)])
                    
                    #calculating the iou 
                    iou=cal_iou(gt,pred)
                    
                    if counter <20:
                        if iou>0.7:
                            temp_img=img_copy[y:y+h+1,x:x+w+1]
                            resize_temp_img=cv2.resize(temp_img,(224,224),interpolation=cv2.INTER_AREA)
                            train_img.append(resize_temp_img)
                            # label the pic containing airplane as 1
                            train_label.append(1)
                            counter+=1
                            
                            
                    else:
                        fflag=1
                        
                    if bcounter<20:
                        if iou<0.3:
                            temp_img=img_copy[y:y+h+1,x:x+w+1]
                            resize_temp_img=cv2.resize(temp_img,(224,224),interpolation=cv2.INTER_AREA)
                            train_img.append(resize_temp_img)
                            # label the background as 0 
                            train_label.append(0)
                            bcounter+=1
                            
                    else:
                        bflag=1
                        
                if fflag ==1 and bflag ==1 :
                    flag=1
                    #print(counter,bcounter)
                        
        
    
        

20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 2

In [10]:
with open("image_data.pkl","wb") as file:
    pickle.dump(train_img,file)
    
file.close()

In [4]:
with open("image_label.pkl","wb") as file:
    pickle.dump(train_label,file)
    
file.close()

In [47]:
#lets randomly pick some of them and plot them 
rand_num=np.random.randint(0,len(train_label))
plt.imshow(train_img[rand_num])
print(train_label[rand_num])
plt.show()


1


In [5]:
train_img=np.array(train_img[:5000])
train_label=np.array(train_label[:5000])

In [6]:
train_img.shape

(5000, 224, 224, 3)

In [7]:
#first import the vdd16 model 
vgg_16=VGG16(weights='imagenet',include_top=True)
vgg_16


In [65]:
vgg_16.input

<KerasTensor: shape=(None, 224, 224, 3) dtype=float32 (created by layer 'input_1')>

In [9]:
#taking the first 15 layer 
for layer in vgg_16.layers[:15]:
    layer.trainable=False
    
#taking till the 2nd last layer 
vgg_model=vgg_16.layers[-2].output
#lats define the last output layers 
prediction=keras.layers.Dense(units=2,activation="softmax")(vgg_model)
final_model=keras.Model(inputs=vgg_16.input,outputs=prediction,)


In [10]:
final_model.compile(optimizer=keras.optimizers.Adam(learning_rate=0.001),loss=keras.losses.sparse_categorical_crossentropy,
                    metrics=['accuracy'])
final_model.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 224, 224, 3)]     0         
                                                                 
 block1_conv1 (Conv2D)       (None, 224, 224, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 224, 224, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 112, 112, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 112, 112, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 112, 112, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 56, 56, 128)       0   

In [11]:
callback=callbacks.ModelCheckpoint(save_best_only=True,
                                   filepath="best_rcnn.h5",
                                   verbose=2,
                                   monitor='val_accuracy',
                                   mode='max'
                                   )
es=EarlyStopping(monitor="val_accuracy",min_delta=0.01,patience=5,verbose=2)
csvlogger=CSVLogger(filename="r_cnn.csv",append=True,separator=",")


In [12]:
#spliting the data into train and test 
x_train,x_test,y_train,y_test=train_test_split(train_img,train_label,test_size=0.15,random_state=42)

In [3]:
#traning the model 
#hist=final_model.fit(x_train,y_train,epochs=20,callbacks=[callback,es,csvlogger],validation_data=[x_test,y_test])


In [4]:
#test data 
ss=cv2.ximgproc.segmentation.createSelectiveSearchSegmentation()
test_img=cv2.imread(os.path.join(path,"428483.jpg"))
copy_test_img=test_img.copy()
ss.setBaseImage(test_img)
ss.switchToSelectiveSearchFast()
rect=ss.process()



In [30]:
rect.shape

(165, 4)

In [5]:
test_img_data=[]
for e in rect:
    x,y,w,h=e 
    temp_img=test_img[y:y+h+1,x:x+w+1] 
    temp_img=cv2.resize(temp_img,(224,224),interpolation = cv2.INTER_AREA)
    test_img_data.append(temp_img)
    
test_img_data=np.array(test_img_data)
test_img_data.shape
    


(246, 224, 224, 3)

In [7]:
"""
with open("test_image_dat.pkl","wb") as file:
    pickle.dump(test_img_data,file)
    
file.close()
"""

In [6]:
#best_model=load_model(os.path.join(r'E:\python\basic code\R-cNN',"best_rcnn.h5"))
prediction=best_model.predict(test_img_data)
#y_pred=np.argmax(prediction[prediction[:,1] > 0.9],axis=1)


8/8 [==============================] - 172s 22s/step


In [51]:
prediction

array([[0.66399586, 0.33600405],
       [0.93973255, 0.06026752],
       [0.87708676, 0.12291323],
       ...,
       [0.9931116 , 0.0068884 ],
       [0.97275317, 0.02724688],
       [0.98469365, 0.0153064 ]], dtype=float32)

In [7]:
test_img=cv2.imread(os.path.join(path,"428483.jpg"))

In [9]:
for num,data in enumerate(prediction):
    if data[1] > 0.80:
        x,y,w,h=rect[num]
        cv2.rectangle(test_img,(x,y),(x+w,y+h),(0,255,0),1,cv2.LINE_AA)
        
        
plt.imshow(test_img)
plt.show()
        